defaults:
  directories:
  - cardboardlint
  include:
  - "*.py"
  exclude: []

linters:
  - import:

  - namespace:
      exclude:
      - "__init__.py"
      - "test_*.py"

  - pylint:
      config_file: .pylintrc
