default_directories:
  - packagename
default_include:
  - "*py"
default_exclude:
  []

import:

namespace:
  exclude:
    - "__init__.py"
    - "test_*.py"

flake8:
  config_file:

pylint:
  default_config_file: pylintrc
  1_config_file: pylintrc_2
  1_include: ["*.py"]

cppcheck:
  include:
    - "*.cpp"
  exclude:
    - "*_inc.cpp"
    - "cext.cpp"

cpplint:

doxygen:
  root: doc
  config_file: doxygen.conf
  warnings: doxygen_warnings.log
