# This is based on the doxygen recipe from conda-forge with some small alterations.
package:
  name: doxygen
  version: 1.8.13

source:
  url: ftp://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.13.src.tar.gz
  fn: doxygen-1.8.13.src.tar.gz
  patches:
  - doxygen_test_patch.diff
  - find_iconv.patch
  - doxygen-1.8.13-NULL-dereference.patch

build:
  number: 0

requirements:
  build:
  - cmake
  - libiconv
  - bison
  - flex
  - gcc
  run:
  - m4
  - libiconv
  - libgcc

test:
  commands:
    - doxygen -v

about:
    home: http://www.stack.nl/~dimitri/doxygen/index.html
    license: GPLv3
